spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      # TODO order-service, product-service의 라우팅 설정을 해주세요! (여기에서 설정하면 GatewayConfig에서 설정하지 않아도 됩니다)
      # 아래는 예시입니다. 삭제 후 실제 코드 추가해주세요!
      - id: order-service
        uri: lb://order-service
        predicates:
          - Path=/orders/create
        filters:
          - name: CustomLog
            args:
              baseMessage: "[order-service : create]"
              logHeaders: true
      - id: order-service-all
        uri: lb://order-service
        predicates:
          - Path=/orders/**
      - id: product-service
        uri: lb://product-service
        predicates:
          - Path=/products/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
